### ISSUE TITLE
[Feature Request] Also work with points of interest, in addition to pins

### ISSUE THREAD

**Issue by skull-squadron** [norio-nomura/CopyLatLngOnMaps#1]
Works great.  It would be even more convenient to also work with businesses, etc. so users don't have to drop an extra pin.

**Comment by norio-nomura** [comment]
I thought it works for any points of interest.
If I will do some change to CopyLatLngOnMaps, I will change it from SIMBL plugin to App Extension working on Yosemite or later.
I will verify this request with those changes in some future.
But as SIMBL plugin, I won't do it.

**Comment by skull-squadron** [comment]
Couldn't understand anything you said, but I fixed it in [my fork](https://github.com/steakknife/CopyLatLngOnMaps) since you apparently were unable to.

**Comment by norio-nomura** [comment]
Sorry my poor english.
I think SIMBL plugins will be not usable on OS X 10.11 by [System Integrity Protection](https://github.com/norio-nomura/EasySIMBL/issues/26), so I thought I need to change it to Share Extension.
